version: "3.7"
services:
  db-prod:
    container_name: db-prod
    image: postgres:9.6
    ports:
      - 5433:5432
    networks:
      - prod_net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=controledespesas
    volumes:
      - prod_postgresql:/var/lib/postgresql
      - prod_postgresql_data:/var/lib/postgresql/data

  backend-prod:
    container_name: app-prod
    image: app:build
    build:
      context: .
      args:
        - WAR_FILE=target/*.war
        - CONTEXT=producao
    networks:
      - prod_net
    ports:
      - 8082:8080
   # environment:
     # - DATABASE_HOST=db-prod
     # - DATABASE_PORT=5432
     # - DATABASE_USER=postgres
     # - DATABASE_PASSWD=postgres
    depends_on:
      - db-prod

networks:
  prod_net:

volumes:
  prod_postgresql:
  prod_postgresql_data: